language: node_js
env:
global:
- REACT_APP_CLIENT_ID=$REACT_APP_CLIENT_ID
node_js:
- "10"
services:
- docker
before_install:
# install heroku CLI
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
install:
- npm install
test:
- npm run test
deploy:
provider: script
script: echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com; heroku container:push web -a $APP_NAME; heroku container:release web -a $APP_NAME;
on:
branch: master
