language: node_js
node_js:
- "10"
services:
- docker
before_install:
# install heroku CLI
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
- echo "creating env files"
- touch ./react-app/.env.production && echo "REACT_APP_CLIENT_ID=$REACT_APP_CLIENT_ID" > ./react-app/.env.production
install:
- echo "skip install"
before_script:
- npm run ci:up
- sleep 2
script:
- echo "pre test"
- docker exec -it app-matteoaffinity npm run test:ci
after_script:
- npm run ci:down
deploy:
  provider: script
  script: ./deploy.sh
on:
branch: master
